- hosts: all
  name: packstack-fedora-pre
  tasks:
    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          cp -pr /home/zuul/src/git.openstack.org/openstack/packstack {{ ansible_user_dir }}/workspace

    - shell:
        cmd: |
          set -e
          set -x
          dnf -y install wget
          rm -rf /etc/yum.repos.d/fedora*
          wget -O /etc/yum.repos.d/fedora-stable.repo http://trunk.rdoproject.org/fedora/delorean-deps.repo
          dnf clean all
          sudo sed -i '/^exclude.*/d' /etc/dnf/dnf.conf
          dnf -y install libxml2-devel libxslt-devel ruby-devel zlib-devel
          dnf -y install gcc gettext diffstat doxygen patch patchutils subversion systemtap git python-setuptools wget redhat-lsb-core libselinux-python yum-plugin-priorities dnf-yum virt-what
          pip uninstall requests -y || true
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      become: true
      environment: '{{ zuul }}'
